### ISSUE TITLE
Rails console oddness

### ISSUE THREAD

**Issue by dfischer** [MarioRicalde/magus#4]
Maybe this is intended:

If I type `rails c`

Then I press up arrow. I hear "system beep" continuously until I press left arrow then up arrow and then I'm able to cycle through past commands. It'll beep until I press left arrow.

**Comment by dfischer** [comment]
this one is so annoying, how to fix?

**Comment by MarioRicalde** [comment]
Have you tried using <ESC> and J ?

**Comment by MarioRicalde** [comment]
`<Esc>` and `J`

**Comment by dfischer** [comment]
Is there any way we can hook in what mode we're in in Rails c?
